ticket/Mapp/urls.py
from django.contrib import admin
from django.urls import path,include
from Mapp import views
app_name='Mapp'
urlpatterns = [
    path('', views.home.as_view(),name="home"),
# path('addmovi', views.addmovie,name="add5"),
# path('add', views.add1,name="add1"),
path('add', views.add1.as_view(),name="add1"),
# path('update/<int:p>', views.update,name="update"),
path('update/<int:pk>', views.update.as_view(),name="update"),
#path('delete/<int:p>', views.delete,name="delete"),
path('delete/<int:pk>', views.delete.as_view(),name="delete"),
# path('view/<int:p>', views.view,name="view"),
path('view/<int:pk>', views.view.as_view(),name="view"),
]

ticket/ticket/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Mapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
path('', include('Mapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ticket/Mapp/models.py
from django.db import models

class movie(models.Model):
    title=models.CharField(max_length=20)
    desc = models.CharField(max_length=20)
    img = models.ImageField(upload_to="travel/img", null=True, blank=True)

ticket/Mapp/forms.py
from django import forms
from Mapp.models import movie
class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields="__all__"

ticket/Mapp/views.py
from django.shortcuts import render
from Mapp.models import movie
from Mapp import views
from Mapp.forms import movieform
from django.views.generic import ListView,DetailView,CreateView,DeleteView,UpdateView
from django.urls import reverse_lazy
# Create your views here.
# def home(request):
#     l=movie.objects.all()
#     return render(request,'home.html',{'l':l})
class home(ListView):
    model=movie
    template_name="home.html"
    context_object_name="l"
# def addmovie(request):
#     if (request.method=="POST"):
#         t=request.POST['t']
#         d=request.POST['d']
#         s=request.POST['s']
#         l=movie.objects.create(title=t,desc=d,img=s)
#         l.save()
#         return home(request)
#     return render(request,'addmovies.html')
# def update(request,p):
#     b=movie.objects.get(id=p)
#     f=movieform(instance=b)
#     if(request.method=="POST"):
#         f=movieform(request.POST,request.FILES,instance=b)
#         if(f.is_valid()):
#             f.save()
#             return home(request)
#     return render(request,'addmovies.html',{'f':f})
"""def add1(request):
    f = movieform()
    if (request.method == "POST"):
        f = movieform(request.POST, request.FILES)
        if (f.is_valid()):
            f.save()
            return home(request)
    return render(request, 'addmovies.html', {'f': f})"""
class add1(CreateView):
    model= movie
    template_name="addmovies.html"
    fields = ['title','desc','img']
    success_url = reverse_lazy('Mapp:home')
# def view(request,p):
#     v=movie.objects.get(id=p)
#     return render(request,'view.html',{'view':v})
class view(DetailView):
    model = movie
    template_name = "view.html"
    context_object_name = "view"
# def delete(request,p):
#     d=movie.objects.get(id=p)
#     d.delete()
#     return home(request)
class delete(DeleteView):
    model=movie
    template_name="delete.html"
    success_url=reverse_lazy('Mapp:home')

class update(UpdateView):
    model = movie
    template_name = "addmovies.html"
    fields = ['title', 'desc', 'img']
    success_url = reverse_lazy('Mapp:home')

ticket/templates/addmovies.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--<form method="POST">-->
<!--    {% csrf_token %}-->
<!--    <div class="mb-3">-->
<!--    <label class="form-label">IMAGE</label>-->
<!--    <input type="file" class="form-control" name="p" placeholder="upload image">-->
<!--    </div>-->
<!--  <div class="mb-3">-->
<!--    <label class="form-label">TITLE</label>-->
<!--    <input type="text" class="form-control" name="t" placeholder="enter title" aria-describedby="emailHelp">-->
<!--  </div>-->
<!--  <div class="mb-3">-->
<!--    <label class="form-label">DESCRIPTION</label>-->
<!--    <input type="text" class="form-control" name="d" placeholder="enter description">-->
<!--  </div>-->

<!--  <button type="submit" class="btn btn-primary">Submit</button>-->
<center>
    <h1>Trending Movies</h1>
    <form method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_p}}
        </table>
        <button type="submit">submit</button>
    </form>
</center>

{% endblock %}

ticket/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
          <link rel="stylesheet" href="{% static 'css/a.css' %}">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="">MOVIE REVIEW</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Mapp:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Mapp:add1' %}">ADD MOVIES</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

ticket/templates/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    Are yOU want to delete this movie??
    <input type="submit">
</form>
{% endblock %}

ticket/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Trending Movies</h1>
<div class="container mt-3">
<div class="row">
  {% for i in l %}
  <div class="col-sm-4">
    <div class="card" style="width: 18rem;">
      <img src="{{ i.img.url }}"  height="200px" width="150px" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{i.title}}</h5>
        <p class="card-text">{{i.desc}}</p>
        <a href="{% url 'Mapp:view' i.id %}" class="btn btn-primary">Knowmore</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
</div>
{% endblock %}

ticket/templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1> VIEW MOVIE DETAILS</h1>
<table class="table table-bordered">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Image</th>
    </tr>
    <tr>
        <td>{{view.title}}</td>
        <td>{{view.desc}}</td>
        <td><img src="{{view.img.url}}" height="100px" width="100px"></td>
        <td><a href="{% url 'Mapp:update' view.id %}" class="btn btn-warning btn-md">update</a></td>
        <td><a href="{% url 'Mapp:delete' view.id %}" class="btn btn-warning btn-md">delete</a></td>
    </tr>
</table>
{% endblock %}